### ISSUE TITLE
Seleção das tabela

### ISSUE THREAD

**Issue by MarceloNikomap** [JohnTendik/jtrt-tables#73]
**[BR]** Olá estou com um problema quando passo o mouse em cima das tabela as partes brancas somem de acordo como vou passando o mouse por cima. - > https://i.imgur.com/D7y663w.gifv  AJUDA?

**[ES]** Hola estoy con un problema cuando paso el ratón sobre la mesa las partes blancas se suman de acuerdo a cómo voy pasando el ratón por encima. - > https://i.imgur.com/D7y663w.gifv AYUDA?

**[EN]** Hello, I'm having a problem when I mouse over the table and the white parts disappear according to how I'm moving the mouse over it. - > https://i.imgur.com/D7y663w.gifv HELP?

**Comment by JohnTendik** [comment]
@MarceloNikomap 

I'll take a look a this for ya. It's probably something dumb that I did =) I'll get back to you when I get a fix.

**Comment by MarceloNikomap** [comment]
Okay =}

**Comment by JohnTendik** [comment]
Hey @MarceloNikomap this has been fixed with the latest update. Let me know if you run into more issues or have any questions. 

Thanks
JT

**Comment by MarceloNikomap** [comment]
Hi the problem still persists I already updated :( https://imgur.com/jT0acVr

**Comment by JohnTendik** [comment]
Hi @MarceloNikomap

Do you have a link for me that i can check out? A live site i can look at to see what may be the problem would lead me to the right direction. Question for you, are you using the cell background option on the table editor or custom styles? 

You can email me at johntendik@hotmail.com that way your link isnt private. 

Thanks
JT

**Comment by MarceloNikomap** [comment]
Your login has been sent to your email Tranks.

**Comment by JohnTendik** [comment]
Hey man, I'm not seeing the problem, try clearing your cache :)

**Comment by MarceloNikomap** [comment]
Thank you now, I'll just use your table. <3
