### ISSUE TITLE
Can't add borders to cells anymore

### ISSUE THREAD

**Issue by Seamate** [JohnTendik/jtrt-tables#94]
Hey John,
Please take a look at your plugin. I tried to create a table and add borders to the cells, but when I clicked the border function to add borders, nothing happens and the borders are not added. 

I did troubleshoot the issue by disabling plugins and switching theme, but the problem persists.

I am running Wordpress version 5.3.2 and PHP version 7.1

Thanks for the awesome plugin bro.

**Comment by JohnTendik** [comment]
Hey, 

I will take a look today, hopefully I can fix it :)

**Comment by JohnTendik** [comment]
Found the issue. Expect a fix sometime tonight :)

**Comment by Seamate** [comment]
That's so relieving to know. Thanks a lot. Expecting...

**Comment by JohnTendik** [comment]
Hey I'm hoping it should be fixed now. Let me know if there are any other issues. Thanks :)

**Comment by Seamate** [comment]
Thanks for the response bro, but the issue persists on my end. Still can't add tables even after updating the plugin to the latest version.

**Comment by JohnTendik** [comment]
Do you have caching enabled? Try doing a hard refresh, the script is probably cached somewhere. Also, just to confirm, you can't add borders or tables?

**Comment by JohnTendik** [comment]
Hey @Seamate did you see my comment?

**Comment by Seamate** [comment]
John,
I just checked again after clearing my cache and rebooting my system. Everything works fine now. The issue was that I could add **borders** to cells. 
You just saved me a lot of stress. 
Thank you, bro.
